### ISSUE TITLE
Suggest naming rules after tasks

### ISSUE THREAD

**Issue by kylebittinger** [zhaoc1/sunbeam_neutrino#2]
Suggest naming rules after the task to be accomplished, rather than the method used to accomplish the task.  This will allow us to focus more closely on configuration and reference databases in the rules file.  Then, if the methods change, the rules will still make sense.  Finally, maybe it will be easier to extract some common logic for methods if we organize the rules like this.

**Comment by zhaoc1** [comment]
Rename blast.rules into bileacid.rules.
